Eclipsefunctions
rstub/swephR pull request #53
Opened 2019-07-17 20:54 UTC by vreijs

Not 100% done yet (need to add the testthat tests for the new functions). 
But I also have an issues when doing roxygen2::roxygenise(). I get warning:
Warning: @details [C:\Users\vrhome\Documents\R\Projects\swephR\R\RcppExports.R#428]: mismatched braces or quotes

2019-07-17 21:50 UTC, vreijs commented
will work on the testthat tests in coming days.

2019-07-18 10:03 UTC, rstub commented
Nice! Is there anything missing from your side? If not, I will merge this PR. Before we can do a CRAN release, I have to figure out #52, though.

BTW, does this mean we now have full coverage of the SE C API?

2019-07-18 10:12 UTC, vreijs commented
I still have this error when doing the roxygen2::roxygenise():
Warning: @details [C:\Users\vrhome\Documents\R\Projects\swephR\R\RcppExports.R#419]: mismatched braces or quotes

Indeed all SE C API are now covered.

2019-07-18 12:09 UTC, rstub requested changes

2019-07-18 12:09 UTC, rstub commented on R/RcppExports.R
> +#' \describe{
The warning comes from this line. Indeed, the brace opened on this line is never closed. However, this is a generated file ...

2019-07-18 12:09 UTC, rstub commented on src/libswe/swecl.c
> -  * V. Reijs, 2000, http://www.iol.ie/~geniet/eng/refract.htm
I will create e new patch file for this change

2019-07-18 12:09 UTC, rstub commented on src/swephR.cpp
> +//' }
The brace opened on line 744 is never closed. This is the reason for the warning. It is probably best to add a closing brace in line 746, similar to other uses of this documentation pattern.

2019-07-18 20:30 UTC, vreijs commented
I have removed the warning of the brackets.

2019-07-19 05:18 UTC, rstub approved these changes

2019-07-19 05:20 UTC, merged

2019-07-19 06:08 UTC, vreijs commented
Thanks!